local clock=0
local key={HOME=5,LEFT=1,RIGHT=2,UP=3,DOWN=4,START=10,SHORT=11,LONG_START=12,LONG_END=13}
local events={}
local I=dofile(ROOT..'/package/input.lua').new(key,function()return clock end,function(...)events[#events+1]={...}end)
I.physical(key.HOME,key.START);I.physical(key.HOME,key.SHORT)
assert(#events==1 and events[1][1]=='confirm')
I.physical(key.HOME,key.START);I.physical(key.HOME,key.LONG_START);I.physical(key.HOME,key.SHORT);I.physical(key.HOME,key.LONG_END)
assert(#events==2 and events[2][1]=='exit')
I.physical(key.LEFT,key.START);I.physical(key.LEFT,key.SHORT)
assert(#events==3 and events[3][1]=='direction' and events[3][3]==-1)
I.pad({connected=true,buttons=16});I.pad({connected=true,buttons=16})
assert(#events==4 and events[4][1]=='confirm')
I.pad({connected=true,buttons=0});I.pad({connected=true,buttons=32})
assert(events[#events][1]=='back')
I.pad({connected=true,buttons=8192});assert(events[#events][1]=='pause')
I.pad({connected=true,buttons=32768});clock=200;I.pad({connected=true,buttons=0})
assert(events[#events][1]=='confirm')
I.pad({connected=true,buttons=32768});clock=1100;I.pad({connected=true,buttons=32768})
assert(events[#events][1]=='exit')
local count=#events;I.pad({connected=true,buttons=0});assert(#events==count)
I.pad({connected=true,buttons=0,lx=20000,ly=0});assert(events[#events][1]=='direction')
count=#events;I.pad({connected=true,buttons=0,lx=22000});assert(#events==count)
I.pad({connected=false});assert(not I.connected)
I.pad({connected=true,buttons=8});assert(events[#events][3]==1)
